apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-secret-provider
  namespace: sample-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a4684117-ad4e-41d3-a178-ba5bf194003a"
    keyvaultName: "kv-hybridlab-dev-7a1w"
    tenantId: "91d162d5-95d2-4868-9184-6f9bf3c87435"
    objects: |
      array:
        - |
          objectName: demo-secret
          objectType: secret
